import { Activity } from '@domain/entities/Activity';

export const ACTIVITY_PRESETS: readonly Activity[] = [
  {
    id: 'preset-walk',
    name: 'Caminhada',
    emoji: '🚶',
    weights: { temperature: 3, precipitation: 4, wind: 2, uv: 1 },
    temperatureC: { idealMin: 16, idealMax: 26, hardMin: 5, hardMax: 36 },
    maxPrecipitationProbability: 50,
    maxWindKmh: 35,
    maxUvIndex: 9,
    isPreset: true,
  },
  {
    id: 'preset-run',
    name: 'Corrida',
    emoji: '🏃',
    weights: { temperature: 4, precipitation: 3, wind: 2, uv: 3 },
    temperatureC: { idealMin: 10, idealMax: 21, hardMin: 2, hardMax: 32 },
    maxPrecipitationProbability: 40,
    maxWindKmh: 30,
    maxUvIndex: 7,
    isPreset: true,
  },
  {
    id: 'preset-cycle',
    name: 'Pedalar',
    emoji: '🚴',
    weights: { temperature: 3, precipitation: 4, wind: 4, uv: 2 },
    temperatureC: { idealMin: 14, idealMax: 26, hardMin: 4, hardMax: 34 },
    maxPrecipitationProbability: 35,
    maxWindKmh: 25,
    maxUvIndex: 8,
    isPreset: true,
  },
  {
    id: 'preset-beach',
    name: 'Praia',
    emoji: '🏖️',
    weights: { temperature: 4, precipitation: 4, wind: 2, uv: 1 },
    temperatureC: { idealMin: 25, idealMax: 33, hardMin: 18, hardMax: 42 },
    maxPrecipitationProbability: 30,
    maxWindKmh: 30,
    maxUvIndex: 11,
    isPreset: true,
  },
  {
    id: 'preset-picnic',
    name: 'Piquenique',
    emoji: '🧺',
    weights: { temperature: 3, precipitation: 5, wind: 4, uv: 2 },
    temperatureC: { idealMin: 18, idealMax: 28, hardMin: 8, hardMax: 36 },
    maxPrecipitationProbability: 20,
    maxWindKmh: 20,
    maxUvIndex: 9,
    isPreset: true,
  },
];
